spring.application.name=ForwardBackend
server.port=8090

spring.datasource.url=jdbc:mysql://forwardagency-forwardagency123.a.aivencloud.com:11740/Forward_Agency?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_cBFnimLAUprwJo22W0y
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.initializationFailTimeout=60000
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
